http:
  host: "0.0.0.0"
  port: "8081"
  path: "/flights"
  pathID: "/flights/{ID}"
mule:
  version: "4.4.0"
  
anypoint:
  username: "Learn2023"
  password: "MuyleSoft2021"
  
  
cloudhub:
  enviroment: "Sandbox"
  app: "training4-american-ws"
  bg: "Learner"
  worker: "Micro"
  
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"
  

  